// ─── High-level orchestrator: prompt → tool calls → store ──────────────────
//
// Calls the model with the tool catalogue (ai/tools), executes every tool
// call the model makes against the live diagram, feeds the results back as
// a single user turn, and repeats until the model returns a plain-text final
// answer (no more tool calls) or `maxIterations` is hit.

import { emptyReport, mergeReport, type ApplyReport, type DiagramFacade } from './diagramFacade'
import { getAdapter } from './registry'
import { buildSystemMessages } from './systemPrompt'
import { buildToolDefs, buildToolHandlers, type ToolRunContext } from './tools'
import { textOf, toolCallsOf, type AISettings, type ChatContentBlock, type ChatMessage } from './types'

export interface RunAIResult {
  summary: string
  report: ApplyReport
  /** Raw assistant text from the last round — useful for debugging. */
  raw: string
  /** How many tool-execution rounds this run took (0 = the model answered directly). */
  iterations: number
  /** New turns generated by this run — append to the caller's persisted history. */
  history: ChatMessage[]
}

export interface RunAIOptions {
  prompt: string
  settings: AISettings
  diagram: DiagramFacade
  history?: ChatMessage[]
  signal?: AbortSignal
  /** Maximum tool-execution rounds before giving up. Default: 12. */
  maxIterations?: number
}

export async function runAIPrompt(opts: RunAIOptions): Promise<RunAIResult> {
  const { settings, prompt, diagram, history = [], signal } = opts
  const maxIterations = opts.maxIterations ?? 12
  const cfg = settings.providers[settings.active]
  const adapter = getAdapter(settings.active)
  const model = cfg.model || adapter.defaultModel

  const metamodel = diagram.getMetamodel?.()
  const tools = buildToolDefs(metamodel)
  const handlers = buildToolHandlers()

  // Shared across the WHOLE run — a node created in round 1 must still be
  // resolvable by a relation created in round 3, and reset_diagram (any
  // round) must invalidate every tempId registered before it.
  const tempToReal = new Map<string, string>()
  let placedThisRun = 0
  const PLACE_X0 = 80
  const PLACE_Y0 = 80
  const STEP_X = 360
  const PER_ROW = 4
  const ctx: ToolRunContext = {
    diagram,
    resolveId: (id) => tempToReal.get(id) ?? id,
    registerTempId: (tempId, realId) => { tempToReal.set(tempId, realId) },
    resetTempIds: () => { tempToReal.clear() },
    placeNext: () => {
      const col = placedThisRun % PER_ROW
      const row = Math.floor(placedThisRun / PER_ROW)
      placedThisRun++
      return { x: PLACE_X0 + col * STEP_X, y: PLACE_Y0 + row * 280 }
    },
  }

  // Working transcript for THIS run — kept separate from the caller's
  // persisted `history` so the caller decides whether/how to carry it forward.
  const turns: ChatMessage[] = [{ role: 'user', content: prompt }]
  const report = emptyReport()
  let lastRaw = ''
  let iterations = 0

  while (true) {
    if (signal?.aborted) throw new Error('Aborted')
    if (iterations >= maxIterations) {
      report.errors = [`Stopped after ${maxIterations} tool-calling rounds without a final answer.`]
      break
    }

    // Re-read live state every round so the model sees whatever the previous
    // round's tool calls just changed.
    const systemMessages = buildSystemMessages(
      diagram.getNodes(),
      diagram.getRelations(),
      metamodel,
      diagram.getActiveView?.() ?? null,
      diagram.getViews?.(),
    )

    const res = await adapter.chat(
      { model, messages: [...systemMessages, ...history, ...turns], tools, maxTokens: 8000, temperature: 0.2, signal },
      cfg,
    )

    // Providers need to see their own prior tool-call ids echoed back on the
    // next turn — push the assistant content verbatim, not just its text.
    turns.push({ role: 'assistant', content: res.content })
    lastRaw = textOf(res.content)

    const calls = toolCallsOf(res.content)
    if (calls.length === 0) {
      return { summary: lastRaw || 'Done.', report, raw: lastRaw, iterations, history: turns }
    }

    if (signal?.aborted) throw new Error('Aborted')

    iterations++
    const resultBlocks: ChatContentBlock[] = []
    const roundErrors: string[] = []
    for (const call of calls) {
      const handler = handlers.get(call.name)
      if (!handler) {
        const msg = `Unknown tool "${call.name}"`
        resultBlocks.push({ type: 'tool_result', toolCallId: call.id, content: msg, isError: true })
        roundErrors.push(msg)
        continue
      }
      let result
      try {
        result = handler(call.input, ctx)
      } catch (err) {
        result = { ok: false, resultText: (err as Error).message }
      }
      resultBlocks.push({ type: 'tool_result', toolCallId: call.id, content: result.resultText, isError: !result.ok })
      if (result.ok) mergeReport(report, result)
      else roundErrors.push(`${call.name}: ${result.resultText}`)
    }
    // Errors are scoped to "still failing this round" — a round with no
    // errors clears whatever the previous round reported, since the model
    // may have just corrected it.
    report.errors = roundErrors
    turns.push({ role: 'user', content: resultBlocks })
  }

  return { summary: lastRaw || 'Stopped.', report, raw: lastRaw, iterations, history: turns }
}
