// ─── High-level orchestrator: prompt → tool calls → store ──────────────────
//
// Calls the model with the tool catalogue (ai/tools), executes every tool
// call the model makes against the live diagram, feeds the results back as
// a single user turn, and repeats until the model returns a plain-text final
// answer (no more tool calls) or `maxIterations` is hit.

import { emptyReport, mergeReport, type ApplyReport, type DiagramFacade } from './diagramFacade'
import { getAdapter } from './registry'
import { buildSystemMessages } from './systemPrompt'
import { buildToolDefs, buildToolHandlers, type ToolRunContext } from './tools'
import { textOf, toolCallsOf, type AISettings, type ChatContentBlock, type ChatMessage } from './types'

export interface RunAIResult {
  summary: string
  report: ApplyReport
  /** Raw assistant text from the last round — useful for debugging. */
  raw: string
  /** How many tool-execution rounds this run took (0 = the model answered directly). */
  iterations: number
  /** New turns generated by this run — append to the caller's persisted history. */
  history: ChatMessage[]
}

/** Live progress, emitted as the loop below works — lets a caller (Radical
 *  Forge) show what's actually happening instead of one static "Generating…"
 *  for the whole run. Purely observational: nothing here changes control
 *  flow or RunAIResult, so callers that don't pass `onProgress` (QuickSearch)
 *  are completely unaffected. */
export type ForgeProgressEvent =
  | { type: 'round'; round: number }
  | { type: 'text'; text: string }
  | { type: 'action'; ok: boolean; label: string }

export interface RunAIOptions {
  prompt: string
  settings: AISettings
  diagram: DiagramFacade
  history?: ChatMessage[]
  signal?: AbortSignal
  /** Maximum tool-execution rounds before giving up. Default: 12. */
  maxIterations?: number
  onProgress?: (event: ForgeProgressEvent) => void
}

/** One human-readable line for a tool call — resolves tempIds/labels through
 *  `ctx` so e.g. an add_relation shows real node labels ("Web App → DB"),
 *  not raw ids. Best-effort: an id that isn't resolvable (yet, or ever)
 *  falls back to the raw id rather than failing. */
function describeToolCall(name: string, input: unknown, ctx: ToolRunContext): string {
  const i = (input ?? {}) as Record<string, unknown>
  const nodeLabel = (id: unknown): string => {
    const resolved = ctx.resolveId(String(id ?? ''))
    return ctx.diagram.getNodes()[resolved]?.label ?? String(id ?? '?')
  }
  switch (name) {
    case 'add_node': return `+ ${String(i.type ?? 'node')}: ${String(i.label ?? '')}`
    case 'update_node': return `~ updated ${String(i.label ?? i.id ?? 'node')}`
    case 'delete_node': return '− removed node'
    case 'add_relation': return `+ ${String(i.relationType ?? 'relation')}: ${nodeLabel(i.sourceId)} → ${nodeLabel(i.targetId)}`
    case 'update_relation': return '~ updated relation'
    case 'delete_relation': return '− removed relation'
    case 'create_view': return `+ view: ${String(i.name ?? '')}`
    case 'set_view_nodes': return '~ updated view'
    case 'set_active_view': return 'switched view'
    case 'delete_view': return '− removed view'
    case 'search_model': return 'searched the model'
    case 'focus_node': return 'focused a node'
    case 'reset_diagram': return 'reset the diagram'
    default: return name
  }
}

export async function runAIPrompt(opts: RunAIOptions): Promise<RunAIResult> {
  const { settings, prompt, diagram, history = [], signal, onProgress } = opts
  const maxIterations = opts.maxIterations ?? 12
  const cfg = settings.providers[settings.active]
  const adapter = getAdapter(settings.active)
  const model = cfg.model || adapter.defaultModel

  const metamodel = diagram.getMetamodel?.()
  const tools = buildToolDefs(metamodel)
  const handlers = buildToolHandlers()

  // Shared across the WHOLE run — a node created in round 1 must still be
  // resolvable by a relation created in round 3, and reset_diagram (any
  // round) must invalidate every tempId registered before it.
  const tempToReal = new Map<string, string>()
  let placedThisRun = 0
  const PLACE_X0 = 80
  const PLACE_Y0 = 80
  const STEP_X = 360
  const PER_ROW = 4
  const ctx: ToolRunContext = {
    diagram,
    resolveId: (id) => tempToReal.get(id) ?? id,
    registerTempId: (tempId, realId) => { tempToReal.set(tempId, realId) },
    resetTempIds: () => { tempToReal.clear() },
    placeNext: () => {
      const col = placedThisRun % PER_ROW
      const row = Math.floor(placedThisRun / PER_ROW)
      placedThisRun++
      return { x: PLACE_X0 + col * STEP_X, y: PLACE_Y0 + row * 280 }
    },
  }

  // Working transcript for THIS run — kept separate from the caller's
  // persisted `history` so the caller decides whether/how to carry it forward.
  const turns: ChatMessage[] = [{ role: 'user', content: prompt }]
  const report = emptyReport()
  let lastRaw = ''
  let iterations = 0
  let round = 0

  while (true) {
    if (signal?.aborted) throw new Error('Aborted')
    if (iterations >= maxIterations) {
      report.errors = [`Stopped after ${maxIterations} tool-calling rounds without a final answer.`]
      break
    }

    round++
    onProgress?.({ type: 'round', round })

    // Re-read live state every round so the model sees whatever the previous
    // round's tool calls just changed.
    const systemMessages = buildSystemMessages(
      diagram.getNodes(),
      diagram.getRelations(),
      metamodel,
      diagram.getActiveView?.() ?? null,
      diagram.getViews?.(),
    )

    const res = await adapter.chat(
      { model, messages: [...systemMessages, ...history, ...turns], tools, maxTokens: 8000, temperature: 0.2, signal },
      cfg,
    )

    // Providers need to see their own prior tool-call ids echoed back on the
    // next turn — push the assistant content verbatim, not just its text.
    turns.push({ role: 'assistant', content: res.content })
    lastRaw = textOf(res.content)
    if (lastRaw) onProgress?.({ type: 'text', text: lastRaw })

    const calls = toolCallsOf(res.content)
    if (calls.length === 0) {
      return { summary: lastRaw || 'Done.', report, raw: lastRaw, iterations, history: turns }
    }

    if (signal?.aborted) throw new Error('Aborted')

    iterations++
    const resultBlocks: ChatContentBlock[] = []
    const roundErrors: string[] = []
    for (const call of calls) {
      const handler = handlers.get(call.name)
      if (!handler) {
        const msg = `Unknown tool "${call.name}"`
        resultBlocks.push({ type: 'tool_result', toolCallId: call.id, content: msg, isError: true })
        roundErrors.push(msg)
        onProgress?.({ type: 'action', ok: false, label: msg })
        continue
      }
      let result
      try {
        result = handler(call.input, ctx)
      } catch (err) {
        result = { ok: false, resultText: (err as Error).message }
      }
      resultBlocks.push({ type: 'tool_result', toolCallId: call.id, content: result.resultText, isError: !result.ok })
      if (result.ok) mergeReport(report, result)
      else roundErrors.push(`${call.name}: ${result.resultText}`)
      onProgress?.({ type: 'action', ok: result.ok, label: result.ok ? describeToolCall(call.name, call.input, ctx) : `${call.name} failed` })
    }
    // Errors are scoped to "still failing this round" — a round with no
    // errors clears whatever the previous round reported, since the model
    // may have just corrected it.
    report.errors = roundErrors
    turns.push({ role: 'user', content: resultBlocks })
  }

  return { summary: lastRaw || 'Stopped.', report, raw: lastRaw, iterations, history: turns }
}
