// ─── Hub visual tokens ───────────────────────────────────────────────────────
//
// Single source of truth for how Hub concepts look — in the standalone hub
// site, the in-app import modal and (via the node-type tokens) the studio
// canvas. A hub *category* is mapped onto the C4 node type it produces, so a
// Requirement card carries the same colour / icon / label as a Requirement
// node on the canvas. `hub/theme.js` is generated from this file
// (`npm run hub:theme`); never edit it by hand.

import type { C4ElementType } from './c4'
import { NODE_COLORS, NODE_FG, TYPE_LABELS, TYPE_ICON_PATHS } from './c4'

export type HubCategory = 'pattern' | 'fitness-function' | 'requirement' | 'adr' | 'blueprint'

export const HUB_CATEGORIES: readonly HubCategory[] = [
  'pattern',
  'fitness-function',
  'requirement',
  'adr',
  'blueprint',
]

export interface VisualToken {
  label: string
  /** Plural form for filter chips / tabs. */
  plural: string
  color: string
  fg: string
  /** SVG path data (16×16 viewBox). */
  iconPath: string
}

/** Node type a hub category materialises as. `pattern` is a bundle of plain
 *  C4 elements and has no dedicated type, so it borrows the System tokens. */
export const CATEGORY_NODE_TYPE: Record<HubCategory, C4ElementType> = {
  pattern: 'system',
  'fitness-function': 'fitness-fn',
  requirement: 'requirement',
  adr: 'adr',
  blueprint: 'blueprint',
}

const CATEGORY_LABELS: Record<HubCategory, { label: string; plural: string }> = {
  pattern: { label: 'Pattern', plural: 'Patterns' },
  'fitness-function': { label: 'Fitness Function', plural: 'Fitness Functions' },
  requirement: { label: 'Requirement', plural: 'Requirements' },
  adr: { label: 'ADR', plural: 'ADRs' },
  blueprint: { label: 'Blueprint', plural: 'Blueprints' },
}

export const CATEGORY_THEME: Record<HubCategory, VisualToken> = Object.fromEntries(
  HUB_CATEGORIES.map((cat) => {
    const type = CATEGORY_NODE_TYPE[cat]
    return [cat, {
      ...CATEGORY_LABELS[cat],
      color: NODE_COLORS[type],
      fg: NODE_FG[type],
      iconPath: TYPE_ICON_PATHS[type],
    }]
  }),
) as Record<HubCategory, VisualToken>

export const NODE_TYPE_THEME: Record<C4ElementType, VisualToken> = Object.fromEntries(
  (Object.keys(NODE_COLORS) as C4ElementType[]).map((type) => [type, {
    label: TYPE_LABELS[type],
    plural: TYPE_LABELS[type] + 's',
    color: NODE_COLORS[type],
    fg: NODE_FG[type],
    iconPath: TYPE_ICON_PATHS[type],
  }]),
) as Record<C4ElementType, VisualToken>

const FALLBACK_TOKEN: VisualToken = {
  label: 'Concept',
  plural: 'Concepts',
  color: '#64748b',
  fg: '#fff',
  iconPath: TYPE_ICON_PATHS.group,
}

export function categoryTheme(category: string): VisualToken {
  return CATEGORY_THEME[category as HubCategory] ?? FALLBACK_TOKEN
}

export function nodeTypeTheme(type: string): VisualToken {
  return NODE_TYPE_THEME[type as C4ElementType] ?? { ...FALLBACK_TOKEN, label: type, plural: type }
}

/** Serializable payload consumed by the vanilla-JS hub site. */
export function buildHubTheme(): {
  categories: Record<HubCategory, VisualToken>
  nodeTypes: Record<C4ElementType, VisualToken>
  fallback: VisualToken
} {
  return { categories: CATEGORY_THEME, nodeTypes: NODE_TYPE_THEME, fallback: FALLBACK_TOKEN }
}

export function renderHubThemeScript(): string {
  return (
    '/* GENERATED by tools/generate-hub-theme.ts from src/renderer/src/types/hubTheme.ts — do not edit. */\n' +
    'window.RADICAL_HUB_THEME = ' +
    JSON.stringify(buildHubTheme(), null, 2) +
    ';\n'
  )
}
