/**
 * The bundled sample model (fintechSampleData.json, generated by
 * tools/generate-sample.js) is the first thing many users open, so it has to
 * stay internally consistent:
 *   - every node sits under a parent the governance metamodel allows
 *   - every typed relation is an allowed pair for its relation type
 *   - mockups live in screen-flow groups, are linked into their flow, have one
 *     presented-by and carry wireframes that are already sanitised
 *   - views, sequences, milestones and slides only reference things that exist
 */
import { describe, it, expect } from 'vitest'
import sample from '../src/renderer/src/store/fintechSampleData.json'
import { builtInGovernanceMetamodel, isParentAllowed } from '@radical/common/metamodel'
import { sanitizeWireframeSvg } from '../src/renderer/src/ai/mockupWireframe'

type Node = { id: string; type: string; parentId?: string; [k: string]: unknown }
type Relation = { id: string; sourceId: string; targetId: string; relationType?: string }

const nodes = sample.nodes as Node[]
const relations = sample.relations as Relation[]
const byId = new Map(nodes.map((n) => [n.id, n]))
const mm = builtInGovernanceMetamodel()

describe('fintech sample model', () => {
  // The C4 core nests domains inside the Core Banking system, which the DDD
  // preset does not formally allow (it expects system-in-domain) — so this
  // checks the governance and product layers only.
  it('places governance and product nodes under an allowed parent', () => {
    const layers = new Set(['adr', 'fitness-fn', 'requirement', 'scenario', 'mockup', 'group'])
    const bad: string[] = []
    for (const n of nodes.filter((n) => layers.has(n.type))) {
      const parent = n.parentId ? byId.get(n.parentId) : undefined
      if (n.parentId) expect(parent, `${n.id}: missing parent`).toBeDefined()
      if (!isParentAllowed(mm, n.type, parent?.type)) bad.push(`${n.id}: ${n.type} in ${parent?.type ?? 'root'}`)
    }
    expect(bad).toEqual([])
  })

  it('uses only metamodel-valid typed relations', () => {
    for (const r of relations) {
      const src = byId.get(r.sourceId)
      const tgt = byId.get(r.targetId)
      expect(src, `${r.id}: missing source`).toBeDefined()
      expect(tgt, `${r.id}: missing target`).toBeDefined()
      if (!r.relationType) continue
      const pairs = mm.relationTypes[r.relationType]?.allowedPairs ?? []
      expect(pairs.some((p) => p.from === src!.type && p.to === tgt!.type), `${r.id}: ${r.relationType} ${src!.type} → ${tgt!.type}`).toBe(true)
    }
  })

  it('showcases the product layer', () => {
    const count = (type: string): number => nodes.filter((n) => n.type === type).length
    expect(count('requirement')).toBeGreaterThanOrEqual(5)
    expect(count('scenario')).toBeGreaterThanOrEqual(3)
    expect(count('mockup')).toBeGreaterThanOrEqual(8)
    const types = new Set(relations.map((r) => r.relationType))
    for (const t of ['derives', 'verifies', 'satisfies', 'traces-to', 'illustrates', 'presented-by', 'navigates-to']) {
      expect(types.has(t), t).toBe(true)
    }
  })

  it('has mockups in screen flows with sanitised wireframes', () => {
    const inFlow = new Set(relations.filter((r) => r.relationType === 'navigates-to').flatMap((r) => [r.sourceId, r.targetId]))
    for (const m of nodes.filter((n) => n.type === 'mockup')) {
      expect(byId.get(m.parentId ?? '')?.type, `${m.id}: not inside a flow group`).toBe('group')
      expect(inFlow.has(m.id), `${m.id}: not linked into its flow`).toBe(true)
      expect(typeof m.screen).toBe('string')
      const wireframe = m.wireframe as string
      expect(wireframe).toMatch(/^<svg /)
      expect(sanitizeWireframeSvg(wireframe)).toBe(wireframe)
      expect(relations.filter((r) => r.sourceId === m.id && r.relationType === 'presented-by')).toHaveLength(1)
    }
  })

  it('references only existing elements from views, sequences, milestones and slides', () => {
    const relIds = new Set(relations.map((r) => r.id))
    const seqIds = new Set(sample.sequences.map((s) => s.id))
    for (const s of sample.sequences) {
      for (const id of s.relationIds) expect(relIds.has(id), `${s.id}: unknown relation ${id}`).toBe(true)
      expect(s.stepDescriptions).toHaveLength(s.relationIds.length)
    }
    for (const v of sample.views as Array<{ id: string; kind: string; sequenceId?: string; nodeIds: string[]; wikiFocusId?: string }>) {
      for (const id of v.nodeIds) expect(byId.has(id), `${v.id}: unknown node ${id}`).toBe(true)
      if (v.kind === 'dynamic') expect(seqIds.has(v.sequenceId!), `${v.id}: unknown sequence`).toBe(true)
      if (v.wikiFocusId) expect(v.nodeIds).toContain(v.wikiFocusId)
    }
    for (const snap of sample.snapshots as Array<{ id: string; nodes: Record<string, Node>; relations: Record<string, Relation> }>) {
      for (const r of Object.values(snap.relations)) {
        expect(snap.nodes[r.sourceId] && snap.nodes[r.targetId], `${snap.id}: ${r.id} dangles`).toBeTruthy()
      }
    }
    const viewIds = new Set(sample.views.map((v) => v.id))
    const snapIds = new Set(sample.snapshots.map((s) => s.id))
    for (const slide of sample.presentations[0].slides) {
      if (slide.viewId) expect(viewIds.has(slide.viewId), slide.id).toBe(true)
      if (slide.snapshotId) expect(snapIds.has(slide.snapshotId), slide.id).toBe(true)
    }
  })
})
